name: ts
channels:
  - defaults
dependencies:
  - python=3.6.6
  - pip:
    - ghp-import==0.5.5
    - jupyterlab==0.33.6
    - nbsphinx==0.3.4
    - sphinx==1.7.6
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.1
    - sphinxcontrib-bibtex==0.4.0